package com.jericx.trainr.data.repository

import com.jericx.trainr.data.local.UserDao
import com.jericx.trainr.data.local.UserMapper
import com.jericx.trainr.domain.model.UserProfile
import com.jericx.trainr.domain.model.WeeklyProgress
import com.jericx.trainr.domain.model.WeeklyWorkoutPlan
import com.jericx.trainr.domain.model.WorkoutDay
import com.jericx.trainr.domain.model.WorkoutDayProgress
import com.jericx.trainr.domain.model.ExerciseSet
import com.jericx.trainr.domain.model.WorkoutExercise
import com.jericx.trainr.domain.model.WorkoutStatus
import com.jericx.trainr.domain.repository.UserRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import javax.inject.Inject

class UserRepositoryImpl @Inject constructor(
    private val userDao: UserDao,
    private val mapper: UserMapper
) : UserRepository {

    override suspend fun saveUser(user: UserProfile): Long {
        return userDao.insertUser(mapper.mapToEntity(user))
    }

    override suspend fun getUser(userId: Long): UserProfile? {
        return userDao.getUserById(userId)?.let { mapper.mapToDomain(it) }
    }

    override suspend fun getCurrentUser(): UserProfile? {
        return userDao.getCurrentUser()?.let { mapper.mapToDomain(it) }
    }

    override suspend fun updateUser(user: UserProfile) {
        userDao.updateUser(mapper.mapToEntity(user))
    }

    override suspend fun hasUsers(): Boolean {
        return userDao.hasUsers()
    }

    override suspend fun saveWeeklyWorkoutPlan(plan: WeeklyWorkoutPlan): Long {
        val planId = userDao.insertWeeklyWorkoutPlan(mapper.mapToEntity(plan))
        saveWorkoutDays(plan.workoutDays, planId)
        return planId
    }

    override fun getWeeklyWorkoutPlans(userId: Long): Flow<List<WeeklyWorkoutPlan>> {
        return userDao.getWeeklyWorkoutPlans(userId).map { planEntities ->
            planEntities.map { planEntity ->
                val days = getWorkoutDaysForPlan(planEntity.id)
                mapper.mapToDomain(planEntity, days)
            }
        }
    }

    override suspend fun getWeeklyWorkoutPlan(userId: Long, weekNumber: Int): WeeklyWorkoutPlan? {
        val planEntity = userDao.getWeeklyWorkoutPlan(userId, weekNumber) ?: return null
        val days = getWorkoutDaysForPlan(planEntity.id)
        return mapper.mapToDomain(planEntity, days)
    }

    override suspend fun updateWeeklyWorkoutPlan(plan: WeeklyWorkoutPlan) {
        userDao.updateWeeklyWorkoutPlan(mapper.mapToEntity(plan))
    }

    override suspend fun saveWorkoutDay(day: WorkoutDay, weeklyPlanId: Long): Long {
        val dayId = userDao.insertWorkoutDay(mapper.mapToEntity(day, weeklyPlanId))

        saveWorkoutExercises(day.exercises, dayId)

        return dayId
    }

    override suspend fun saveWorkoutDays(days: List<WorkoutDay>, weeklyPlanId: Long) {
        val dayEntities = days.map { day ->
            mapper.mapToEntity(day, weeklyPlanId)
        }
        // Room returns the autogenerated row ids here; the entities themselves still
        // carry id = 0 for new rows, so the exercises must be keyed off these.
        val dayIds = userDao.insertWorkoutDays(dayEntities)

        // One exercise at a time rather than a bulk insert: the sets need the
        // generated exercise id, and a bulk insert does not hand it back.
        days.forEachIndexed { dayIndex, day ->
            saveWorkoutExercises(day.exercises, dayIds[dayIndex])
        }
    }

    override suspend fun getWorkoutDaysForPlan(weeklyPlanId: Long): List<WorkoutDay> {
        val dayEntities = userDao.getWorkoutDaysForPlan(weeklyPlanId)
        return dayEntities.map { dayEntity ->
            val exercises = getExercisesForWorkoutDay(dayEntity.id)
            mapper.mapToDomain(dayEntity, exercises)
        }
    }

    override suspend fun getWorkoutDay(dayId: Long): WorkoutDay? {
        val dayEntity = userDao.getWorkoutDayById(dayId) ?: return null
        val exercises = getExercisesForWorkoutDay(dayId)
        return mapper.mapToDomain(dayEntity, exercises)
    }

    override suspend fun updateWorkoutDay(day: WorkoutDay, weeklyPlanId: Long) {
        userDao.updateWorkoutDay(mapper.mapToEntity(day, weeklyPlanId))
    }

    override suspend fun saveWorkoutExercise(exercise: WorkoutExercise, workoutDayId: Long): Long {
        val exerciseId = userDao.insertWorkoutExercise(mapper.mapToEntity(exercise, workoutDayId))
        saveSetsFor(exercise, exerciseId)
        return exerciseId
    }

    override suspend fun saveWorkoutExercises(exercises: List<WorkoutExercise>, workoutDayId: Long) {
        exercises.forEach { saveWorkoutExercise(it, workoutDayId) }
    }

    override suspend fun getExercisesForWorkoutDay(workoutDayId: Long): List<WorkoutExercise> {
        val exerciseEntities = userDao.getExercisesForWorkoutDay(workoutDayId)
        return exerciseEntities.map { entity ->
            mapper.mapToDomain(entity).copy(sets = setsFor(entity.id))
        }
    }

    override suspend fun getWorkoutExercise(exerciseId: Long): WorkoutExercise? {
        return userDao.getWorkoutExerciseById(exerciseId)?.let {
            mapper.mapToDomain(it).copy(sets = setsFor(it.id))
        }
    }

    override suspend fun updateExerciseSet(set: ExerciseSet, workoutExerciseId: Long) {
        userDao.updateExerciseSet(mapper.mapToEntity(set, workoutExerciseId))
    }

    override suspend fun addExerciseSet(set: ExerciseSet, workoutExerciseId: Long): Long {
        return userDao.insertExerciseSet(mapper.mapToEntity(set, workoutExerciseId))
    }

    override suspend fun getPreviousSets(
        userId: Long,
        exerciseKey: String,
        excludeDayId: Long,
        beforeMillis: Long
    ): List<ExerciseSet> {
        return userDao.getPreviousExerciseSets(userId, exerciseKey, excludeDayId, beforeMillis)
            .map { mapper.mapToDomain(it) }
    }

    // Room hands back the generated row id here; the domain objects still carry
    // id = 0 for new rows, so the sets have to be keyed off it.
    private suspend fun saveSetsFor(exercise: WorkoutExercise, exerciseId: Long) {
        if (exercise.sets.isEmpty()) return

        userDao.insertExerciseSets(exercise.sets.map { mapper.mapToEntity(it, exerciseId) })
    }

    private suspend fun setsFor(exerciseId: Long): List<ExerciseSet> =
        userDao.getSetsForExercise(exerciseId).map { mapper.mapToDomain(it) }

    override suspend fun updateWorkoutExercise(exercise: WorkoutExercise, workoutDayId: Long) {
        userDao.updateWorkoutExercise(mapper.mapToEntity(exercise, workoutDayId))
    }

    override suspend fun getWeeklyProgress(userId: Long, weekNumber: Int): WeeklyProgress? {
        val plan = getWeeklyWorkoutPlan(userId, weekNumber) ?: return null
        val dayProgressList = getWorkoutDayProgress(plan.id)
        
        val completedWorkouts = dayProgressList.count { it.status == WorkoutStatus.COMPLETED }
        val totalWorkouts = dayProgressList.size
        val completionPercentage = if (totalWorkouts > 0) {
            (completedWorkouts.toFloat() / totalWorkouts.toFloat()) * 100f
        } else 0f
        
        return WeeklyProgress(
            weekNumber = weekNumber,
            completedWorkouts = completedWorkouts,
            totalWorkouts = totalWorkouts,
            completionPercentage = completionPercentage,
            workoutDays = dayProgressList
        )
    }

    override suspend fun getWorkoutDayProgress(weeklyPlanId: Long): List<WorkoutDayProgress> {
        val dayEntities = userDao.getWorkoutDaysForPlan(weeklyPlanId)
        return dayEntities.map { dayEntity ->
            val totalExercises = userDao.getTotalExercisesForDay(dayEntity.id)
            val completedExercises = userDao.getCompletedExercisesForDay(dayEntity.id)
            val completionPercentage = if (totalExercises > 0) {
                (completedExercises.toFloat() / totalExercises.toFloat()) * 100f
            } else 0f
            
            WorkoutDayProgress(
                dayNumber = dayEntity.dayNumber,
                title = dayEntity.title,
                status = WorkoutStatus.valueOf(dayEntity.status),
                completionPercentage = completionPercentage,
                completedExercises = completedExercises,
                totalExercises = totalExercises
            )
        }
    }
}